<?php

namespace AppBundle\Repository;

/**
 * internshipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class internshipRepository extends \Doctrine\ORM\EntityRepository
{
}
